# Generated by Django 3.1.4 on 2020-12-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_movie_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='category',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='category_domain',
            new_name='img',
        ),
    ]
