# Generated by Django 3.1.4 on 2020-12-16 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201216_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('actor', models.CharField(max_length=60)),
                ('rate', models.FloatField()),
                ('img', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.movies'),
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
